# Generated by Django 3.2 

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dance/')),
                ('upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DanceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=20, null=True)),
                ('file', models.FileField(upload_to='dance_feature/')),
            ],
        ),
        migrations.CreateModel(
            name='MusicSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=20, null=True)),
                ('file', models.FileField(upload_to='music_seed/')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='music/')),
                ('completed', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('dance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.dance')),
            ],
        ),
    ]
