# Generated by Django 3.2.3 

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='combine',
            field=models.FileField(null=True, upload_to='combine/'),
        ),
    ]
